services:

  home-automation-server:
    ports:
      - "502:1502"
    restart: always
    volumes:
      - /d/Docker/HomeAutomationServer/Settings.xml:/app/Settings.xml
      - /d/Docker/HomeAutomationServer/EnergyHistory-2456552877.log:/var/log/EnergyHistory-2456552877.log
    user: app
    build:
      context: .
      dockerfile: HomeAutomationServer/Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    environment:
      - HOME_AUTOMATION_SECRET=Djd./.ed$0|ks.c!eii\e6
