// ReSharper disable IdentifierTypo
// Global using directives

global using System;
global using System.Collections.ObjectModel;
global using System.ComponentModel;
global using System.ComponentModel.Design;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Globalization;
global using System.IO;
global using System.Net;
global using System.Runtime.InteropServices;
global using System.Security.Cryptography;
global using System.Text;
global using System.Text.RegularExpressions;
global using System.Windows;
global using System.Windows.Controls;
global using System.Windows.Controls.Primitives;
global using System.Windows.Data;
global using System.Windows.Input;
global using System.Windows.Interop;
global using System.Windows.Markup;
global using System.Windows.Media;
global using System.Windows.Media.Animation;
global using System.Windows.Threading;
global using System.Xml;
global using System.Xml.Serialization;
global using De.Hochstaetter.Fronius;
global using De.Hochstaetter.Fronius.Contracts;
global using De.Hochstaetter.Fronius.Extensions;
global using De.Hochstaetter.Fronius.Localization;
global using De.Hochstaetter.Fronius.Models;
global using De.Hochstaetter.Fronius.Models.Charging;
global using De.Hochstaetter.Fronius.Models.Gen24;
global using De.Hochstaetter.Fronius.Models.Gen24.Settings;
global using De.Hochstaetter.Fronius.Models.ToshibaAc;
global using De.Hochstaetter.Fronius.Services;
global using De.Hochstaetter.FroniusMonitor.Assets.Images;
global using De.Hochstaetter.FroniusMonitor.AttachedProperties;
global using De.Hochstaetter.FroniusMonitor.Controls;
global using De.Hochstaetter.FroniusMonitor.Extensions;
global using De.Hochstaetter.FroniusMonitor.Models;
global using De.Hochstaetter.FroniusMonitor.Models.CarCharging;
global using De.Hochstaetter.FroniusMonitor.ViewModels;
global using De.Hochstaetter.FroniusMonitor.Views;
global using De.Hochstaetter.FroniusMonitor.Wpf.Commands;
global using De.Hochstaetter.FroniusShared.Contracts;
global using De.Hochstaetter.FroniusShared.Models;
global using De.Hochstaetter.FroniusShared.Services;
global using Microsoft.Win32;
global using Newtonsoft.Json.Linq;
global using SafeHeapMarshalling = System.Diagnostics.DebuggerNonUserCodeAttribute;
global using BigEndianMarshalling = System.Diagnostics.DebuggerHiddenAttribute;
global using Loc = De.Hochstaetter.Fronius.Localization.Resources;
