<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<LangVersion>preview</LangVersion>
		<Configuration>Release</Configuration>
		<RootNamespace>De.Hochstaetter.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
		<AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
		<PublishTrimmed>false</PublishTrimmed>
	</PropertyGroup>

	<ItemGroup>
		<AvaloniaResource Include="Assets\Images\sun.ico" />
	</ItemGroup>

	<ItemGroup>
		<None Remove="Assets\Images\sun.ico" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" Version="$(AvaloniaVersion)" />
		<PackageReference Include="Avalonia.Themes.Fluent" Version="$(AvaloniaVersion)" />
		<PackageReference Include="Avalonia.Fonts.Inter" Version="$(AvaloniaVersion)" />
		<!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
		<PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3">
			<IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
			<PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.11" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Fronius\Fronius.csproj" />
	</ItemGroup>

</Project>
