//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace De.Hochstaetter.Fronius.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("De.Hochstaetter.Fronius.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied.
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AC current.
        /// </summary>
        public static string AcCurrent {
            get {
                return ResourceManager.GetString("AcCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AC line voltage.
        /// </summary>
        public static string ACLineVoltage {
            get {
                return ResourceManager.GetString("ACLineVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AC phase voltage.
        /// </summary>
        public static string AcPhaseVoltage {
            get {
                return ResourceManager.GetString("AcPhaseVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AC power.
        /// </summary>
        public static string AcPower {
            get {
                return ResourceManager.GetString("AcPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AC voltage.
        /// </summary>
        public static string AcVoltage {
            get {
                return ResourceManager.GetString("AcVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apparent power.
        /// </summary>
        public static string ApparentPower {
            get {
                return ResourceManager.GetString("ApparentPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fronius Monitor.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booting.
        /// </summary>
        public static string Booting {
            get {
                return ResourceManager.GetString("Booting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charging.
        /// </summary>
        public static string Charging {
            get {
                return ResourceManager.GetString("Charging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DC current.
        /// </summary>
        public static string DcCurrent {
            get {
                return ResourceManager.GetString("DcCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DC power.
        /// </summary>
        public static string DcPower {
            get {
                return ResourceManager.GetString("DcPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DC voltage.
        /// </summary>
        public static string DcVoltage {
            get {
                return ResourceManager.GetString("DcVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discharging.
        /// </summary>
        public static string Discharging {
            get {
                return ResourceManager.GetString("Discharging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efficiency.
        /// </summary>
        public static string Efficiency {
            get {
                return ResourceManager.GetString("Efficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy.
        /// </summary>
        public static string Energy {
            get {
                return ResourceManager.GetString("Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Settings.
        /// </summary>
        public static string ExportSettings {
            get {
                return ResourceManager.GetString("ExportSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fans.
        /// </summary>
        public static string Fans {
            get {
                return ResourceManager.GetString("Fans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        public static string Idle {
            get {
                return ResourceManager.GetString("Idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include inverter power (Solar web mode).
        /// </summary>
        public static string IncludeInverterPower {
            get {
                return ResourceManager.GetString("IncludeInverterPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect response from data manager.
        /// </summary>
        public static string IncorrectData {
            get {
                return ResourceManager.GetString("IncorrectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        public static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverter.
        /// </summary>
        public static string Inverter {
            get {
                return ResourceManager.GetString("Inverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverters.
        /// </summary>
        public static string Inverters {
            get {
                return ResourceManager.GetString("Inverters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line voltage.
        /// </summary>
        public static string LineVoltage {
            get {
                return ResourceManager.GetString("LineVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Settings.
        /// </summary>
        public static string LoadSettings {
            get {
                return ResourceManager.GetString("LoadSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart meter.
        /// </summary>
        public static string Meter {
            get {
                return ResourceManager.GetString("Meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Meters.
        /// </summary>
        public static string Meters {
            get {
                return ResourceManager.GetString("Meters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        public static string Misc {
            get {
                return ResourceManager.GetString("Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My solar system.
        /// </summary>
        public static string MySolarSystem {
            get {
                return ResourceManager.GetString("MySolarSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not specify complete Fritz!Box connection parameters.
        /// </summary>
        public static string NoFritzBoxConnection {
            get {
                return ResourceManager.GetString("NoFritzBoxConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not specify complete inverter connection parameters.
        /// </summary>
        public static string NoSystemConnection {
            get {
                return ResourceManager.GetString("NoSystemConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ohm pilot.
        /// </summary>
        public static string Ohmpilot {
            get {
                return ResourceManager.GetString("Ohmpilot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ohm Pilots.
        /// </summary>
        public static string Ohmpilots {
            get {
                return ResourceManager.GetString("Ohmpilots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of balance.
        /// </summary>
        public static string OutOfBalance {
            get {
                return ResourceManager.GetString("OutOfBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase voltage.
        /// </summary>
        public static string PhaseVoltage {
            get {
                return ResourceManager.GetString("PhaseVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait ....
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        public static string Power {
            get {
                return ResourceManager.GetString("Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power factor.
        /// </summary>
        public static string PowerFactor {
            get {
                return ResourceManager.GetString("PowerFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power flow.
        /// </summary>
        public static string PowerFlow {
            get {
                return ResourceManager.GetString("PowerFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter supplied by your grid provider.
        /// </summary>
        public static string ProviderMeter {
            get {
                return ResourceManager.GetString("ProviderMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reactive Power.
        /// </summary>
        public static string ReactivePower {
            get {
                return ResourceManager.GetString("ReactivePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real power.
        /// </summary>
        public static string RealPower {
            get {
                return ResourceManager.GetString("RealPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor.
        /// </summary>
        public static string SensorCard {
            get {
                return ResourceManager.GetString("SensorCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensors.
        /// </summary>
        public static string SensorCards {
            get {
                return ResourceManager.GetString("SensorCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Settings Files (*.fms)|*.fms.
        /// </summary>
        public static string SettingsFilter {
            get {
                return ResourceManager.GetString("SettingsFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleeping.
        /// </summary>
        public static string Sleeping {
            get {
                return ResourceManager.GetString("Sleeping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar panels.
        /// </summary>
        public static string SolarPanels {
            get {
                return ResourceManager.GetString("SolarPanels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standby.
        /// </summary>
        public static string Standby {
            get {
                return ResourceManager.GetString("Standby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting.
        /// </summary>
        public static string Starting {
            get {
                return ResourceManager.GetString("Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting (1/7).
        /// </summary>
        public static string StartUp0 {
            get {
                return ResourceManager.GetString("StartUp0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting (2/7).
        /// </summary>
        public static string StartUp1 {
            get {
                return ResourceManager.GetString("StartUp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting (3/7).
        /// </summary>
        public static string StartUp2 {
            get {
                return ResourceManager.GetString("StartUp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting (4/7).
        /// </summary>
        public static string StartUp3 {
            get {
                return ResourceManager.GetString("StartUp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting (5/7).
        /// </summary>
        public static string StartUp4 {
            get {
                return ResourceManager.GetString("StartUp4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting (6/7).
        /// </summary>
        public static string StartUp5 {
            get {
                return ResourceManager.GetString("StartUp5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting (7/7).
        /// </summary>
        public static string StartUp6 {
            get {
                return ResourceManager.GetString("StartUp6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string STATE_DISCONNECTED {
            get {
                return ResourceManager.GetString("STATE_DISCONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string STATE_ERROR {
            get {
                return ResourceManager.GetString("STATE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string STATE_READY {
            get {
                return ResourceManager.GetString("STATE_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string STATE_RUNNING {
            get {
                return ResourceManager.GetString("STATE_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting.
        /// </summary>
        public static string STATE_STARTUP {
            get {
                return ResourceManager.GetString("STATE_STARTUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        public static string STATE_STOPPED {
            get {
                return ResourceManager.GetString("STATE_STOPPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string STATE_UNKNOWN {
            get {
                return ResourceManager.GetString("STATE_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string STATE_WARNING {
            get {
                return ResourceManager.GetString("STATE_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        public static string Storage {
            get {
                return ResourceManager.GetString("Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} at {1:N0} W of power.
        /// </summary>
        public static string StoragePowerMessage {
            get {
                return ResourceManager.GetString("StoragePowerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storages.
        /// </summary>
        public static string Storages {
            get {
                return ResourceManager.GetString("Storages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String control.
        /// </summary>
        public static string StringControl {
            get {
                return ResourceManager.GetString("StringControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String Controls.
        /// </summary>
        public static string StringControls {
            get {
                return ResourceManager.GetString("StringControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperatures.
        /// </summary>
        public static string Temperatures {
            get {
                return ResourceManager.GetString("Temperatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating.
        /// </summary>
        public static string Updating {
            get {
                return ResourceManager.GetString("Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltage.
        /// </summary>
        public static string Voltage {
            get {
                return ResourceManager.GetString("Voltage", resourceCulture);
            }
        }
    }
}
