//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace De.Hochstaetter.Fronius.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("De.Hochstaetter.Fronius.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booting.
        /// </summary>
        public static string Booting {
            get {
                return ResourceManager.GetString("Booting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        public static string Idle {
            get {
                return ResourceManager.GetString("Idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect response from data manager.
        /// </summary>
        public static string IncorrectData {
            get {
                return ResourceManager.GetString("IncorrectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        public static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverter.
        /// </summary>
        public static string Inverter {
            get {
                return ResourceManager.GetString("Inverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverters.
        /// </summary>
        public static string Inverters {
            get {
                return ResourceManager.GetString("Inverters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart meter.
        /// </summary>
        public static string Meter {
            get {
                return ResourceManager.GetString("Meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Meters.
        /// </summary>
        public static string Meters {
            get {
                return ResourceManager.GetString("Meters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My solar system.
        /// </summary>
        public static string MySolarSystem {
            get {
                return ResourceManager.GetString("MySolarSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not specify complete connection parameters.
        /// </summary>
        public static string NoSystemConnection {
            get {
                return ResourceManager.GetString("NoSystemConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ohm pilot.
        /// </summary>
        public static string Ohmpilot {
            get {
                return ResourceManager.GetString("Ohmpilot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ohm Pilots.
        /// </summary>
        public static string Ohmpilots {
            get {
                return ResourceManager.GetString("Ohmpilots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor.
        /// </summary>
        public static string SensorCard {
            get {
                return ResourceManager.GetString("SensorCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensors.
        /// </summary>
        public static string SensorCards {
            get {
                return ResourceManager.GetString("SensorCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleeping.
        /// </summary>
        public static string Sleeping {
            get {
                return ResourceManager.GetString("Sleeping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standby.
        /// </summary>
        public static string Standby {
            get {
                return ResourceManager.GetString("Standby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting (1/7).
        /// </summary>
        public static string StartUp0 {
            get {
                return ResourceManager.GetString("StartUp0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting (2/7).
        /// </summary>
        public static string StartUp1 {
            get {
                return ResourceManager.GetString("StartUp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting (3/7).
        /// </summary>
        public static string StartUp2 {
            get {
                return ResourceManager.GetString("StartUp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting (4/7).
        /// </summary>
        public static string StartUp3 {
            get {
                return ResourceManager.GetString("StartUp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting (5/7).
        /// </summary>
        public static string StartUp4 {
            get {
                return ResourceManager.GetString("StartUp4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting (6/7).
        /// </summary>
        public static string StartUp5 {
            get {
                return ResourceManager.GetString("StartUp5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting (7/7).
        /// </summary>
        public static string StartUp6 {
            get {
                return ResourceManager.GetString("StartUp6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        public static string Storage {
            get {
                return ResourceManager.GetString("Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storages.
        /// </summary>
        public static string Storages {
            get {
                return ResourceManager.GetString("Storages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String control.
        /// </summary>
        public static string StringControl {
            get {
                return ResourceManager.GetString("StringControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String Controls.
        /// </summary>
        public static string StringControls {
            get {
                return ResourceManager.GetString("StringControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
    }
}
